# Generated by Django 3.0.6 on 2020-10-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
