# Generated by Django 3.0.6 on 2020-10-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=300)),
                ('Student_email', models.CharField(max_length=300)),
                ('wrong_ans', models.IntegerField()),
                ('right_ans', models.IntegerField()),
                ('test_status', models.BooleanField()),
                ('total_marks', models.IntegerField()),
                ('test_class', models.CharField(max_length=100)),
            ],
        ),
    ]
