# Generated by Django 3.0.6 on 2020-10-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_score',
            name='score_obtained',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
