# Generated by Django 3.0.6 on 2020-10-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0002_test_score_score_obtained'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=300)),
                ('Student_email', models.CharField(max_length=300)),
                ('test_status', models.BooleanField()),
            ],
        ),
    ]
